### ISSUE TITLE
Requests should extend the lifetime of a CAS TGT

### ISSUE THREAD

**Issue by hannahwhy** [NUARIG/aker#7]
At NUBIC, we use a customized Jasig CAS server that supports extension of TGT lifetimes via proxy ticket requests.  
Interactive requests to webapps that use Aker's `cas` mode should extend the lifetimes of all TGTs associated with that request.

For those who are wondering why in the world we'd ever do this sort of thing, this serves two purposes.  First, it ensures that CAS-proxied requests to services will behave consistently over the entire lifetime of a user's session in all CAS-using applications she visits, not just for some fixed period of time after login.  

Second, it helps us detect when an application session has become stale, i.e. when a session in a CAS-using app has an expired CAS session, which can happen if a user leaves an application idle for a while and the application doesn't enforce session timeouts.

**Comment by hannahwhy** [comment]
Proposed configuration additions:

``` yaml
cas:
  proxy_callback_url: ...
  proxy_retrieval_url: ...
  tgt_timeout: 1800 # seconds
  refresh_anticipation: 30 # seconds; defaults to 60
```
